import {VERSION,WORDS,scoreRecall,recallDetails,recordMathAnswer,nextList,digits,validateRecords} from './core.js';
const app=document.querySelector('#app'), KEY='memoria-em-dia-v1';
let records=[],storageError='',session=null,tick=null,cancelTimer=null;
try{records=validateRecords(JSON.parse(localStorage.getItem(KEY)||'[]'));}catch{storageError='Não foi possível ler o histórico. Exporte os dados originais antes de continuar; não sobrescreveremos seu histórico.';}
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>new Date(value).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
function stop(){clearInterval(tick);tick=null;if(cancelTimer){const cancel=cancelTimer;cancelTimer=null;cancel();}}
function render(html){app.innerHTML=html;window.scrollTo(0,0);}
function download(content,name){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function home(){stop();session=null;const last=records.at(-1);render(`
 <section class="hero"><span class="eyebrow">Acompanhamento de memória</span><h1>Um momento de atenção.<br>Um registro no tempo.</h1><p>Observe seu desempenho em tarefas de memória imediata e após alguns minutos, sempre com a mesma sequência.</p><div class="row"><button id="start" ${storageError?'disabled':''}>Começar uma sessão →</button><span class="muted">Cerca de 9 minutos · sem distrações</span></div></section>
 ${storageError?`<p class="error">${escape(storageError)}</p>`:''}
 <div class="grid"><section class="card"><span class="eyebrow">Sessões registradas</span><p class="number">${records.length}</p><small>Histórico neste aparelho</small></section><section class="card"><span class="eyebrow">Última sessão</span><p class="number" style="font-size:26px">${last?date(last.date):'Ainda não há'}</p><small>${last?'Protocolo '+last.version:'Seu primeiro registro começa aqui'}</small></section><section class="card tint"><span class="eyebrow">Ritmo sugerido</span><p class="number">Semanal</p><small>Uma convenção do app, sem validação clínica</small></section></div>
 <section class="card"><h2>O que você vai fazer</h2><p>1. Repetir seis sequências de dígitos.<br>2. Ver oito palavras e escrever as que lembrar.<br>3. Fazer contas simples por cinco minutos.<br>4. Escrever novamente as palavras que lembrar.</p><p class="note">Protocolo experimental com execução fixa, sem normas clínicas. Repetição, dificuldade das listas, sono e atenção afetam o resultado. O app não determina se sua memória está piorando. A lembrança após cinco minutos não mede memória de dias ou semanas.</p><details><summary>Como manter sessões comparáveis</summary><p>Use o mesmo aparelho, em horário e ambiente semelhantes. Reserve nove minutos, ative Não Perturbe e evite ajuda, anotações, capturas de tela ou ensaio das palavras. Sair do app interrompe a sessão. As listas se alternam, mas não têm dificuldade equivalente comprovada; a primeira sessão também envolve familiarização.</p><p>Se perceber piora persistente ou dificuldades nas atividades do dia a dia, procure avaliação profissional, mesmo com bons resultados aqui.</p><p>Referências: <a href="https://www.nia.nih.gov/health/health-care-professionals-information/assessing-cognitive-impairment-older-patients" target="_blank" rel="noopener">National Institute on Aging</a> e <a href="https://www.nice.org.uk/guidance/ng97/chapter/Recommendations" target="_blank" rel="noopener">NICE</a>. Elas orientam a interpretação e a busca de avaliação; não validam este protocolo.</p></details></section>
 <section class="card"><h2>Seu histórico</h2><p>Resultados por tarefa, sem nota global ou classificação de saúde.</p>${records.length?`<h3>Lembrança após cinco minutos · últimas 12 sessões</h3><div class="bars" aria-hidden="true">${records.slice(-12).map(r=>`<div class="bar" style="height:${r.delayed/8*100}%"><span>${r.delayed}/8</span></div>`).join('')}</div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Dígitos /6</th><th>Imediata /8</th><th>Após 5 min /8</th><th>Sono</th><th>Estresse</th><th>Lista</th><th>Contas: acertos / respostas</th><th>Observações</th><th>Palavras</th></tr></thead><tbody>${[...records].reverse().map(r=>`<tr><td>${date(r.date)}</td><td>${r.digits}</td><td>${r.immediate}</td><td>${r.delayed}</td><td>${r.context.sleep} h</td><td>${escape(r.context.stress)}</td><td>${r.list+1}</td><td>${r.math?`${r.math.correct} / ${r.math.attempted}`:"Não registrado"}</td><td>${escape(r.context.notes)}</td><td><button class="secondary" data-review="${escape(r.id)}">Ver palavras</button></td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhuma sessão ainda. Os resultados aparecerão aqui.</p>'}<div class="row" style="margin-top:24px"><button class="secondary" id="export">Exportar backup</button><label class="button secondary" for="import">Restaurar backup</label><input type="file" id="import" accept="application/json,.json" hidden style="display:none"></div><p id="import-status" role="status"></p><small>Dados apenas neste navegador, sem envio ao servidor. Limpar os dados do site ou trocar de aparelho pode apagar o histórico. Exporte backups para o app Arquivos. O Safari e o app da Tela de Início podem ter históricos separados.</small></section>
 <details><summary>Adicionar ao iPhone</summary><p>Com o site publicado em HTTPS, abra no Safari → Compartilhar → Adicionar à Tela de Início → Adicionar. Abra uma vez com internet para preparar o uso offline. Faça as sessões sempre pelo mesmo atalho.</p></details>`);
 document.querySelector('#start').onclick=setup;
 document.querySelectorAll('[data-review]').forEach(button=>button.onclick=()=>{const result=records.find(r=>r.id===button.dataset.review);render(`<section class="hero"><span class="eyebrow">Sessão de ${date(result.date)}</span><h1>As palavras da sua sessão.</h1></section>${review(result)}<button id="home">Voltar ao histórico</button>`);document.querySelector('#home').onclick=home;});
 document.querySelector('#export').onclick=()=>download(storageError?(localStorage.getItem(KEY)||'[]'):JSON.stringify(records,null,2),'memoria-backup.json');
 document.querySelector('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Arquivo muito grande.');if(storageError)throw Error('Exporte o histórico original antes de reparar o armazenamento.');const incoming=validateRecords(JSON.parse(await file.text()));const merged=validateRecords([...new Map([...incoming,...records].map(r=>[r.id,r])).values()].sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)));localStorage.setItem(KEY,JSON.stringify(merged));records=merged;home();document.querySelector('#import-status').textContent='Backup restaurado; sessões existentes preservadas.';}catch(error){document.querySelector('#import-status').textContent=error.message;}};
}
function setup(){render(`<section class="card"><span class="eyebrow">Antes de começar</span><h1>Como você está hoje?</h1><p>Reserve cerca de nove minutos. Os tempos são fixos. Mantenha o app aberto e não consulte anotações.</p>${records.length&&Date.now()-Date.parse(records.at(-1).date)<6*86400000?'<p class="note">Você fez uma sessão recentemente. A prática pode melhorar os resultados; considere manter o intervalo semanal.</p>':''}<form id="setup"><label>Horas de sono na última noite<input name="sleep" type="number" min="0" max="24" step="0.5" required placeholder="Ex.: 7.5"></label><label>Estresse agora<select name="stress"><option>Baixo</option><option>Médio</option><option>Alto</option></select></label><label>Observações (opcional)<input name="notes" maxlength="500" placeholder="Ex.: cansaço, mudança de rotina"></label><p>Você verá um dígito por vez. Depois, digite a sequência na mesma ordem. Serão duas sequências de cada tamanho: 3, 4 e 5 dígitos.</p><div class="row"><button>Iniciar teste</button><button type="button" class="secondary" id="back">Voltar</button></div></form></section>`);document.querySelector('#back').onclick=home;document.querySelector('#setup').onsubmit=e=>{e.preventDefault();try{localStorage.setItem('memoria-storage-test','1');localStorage.removeItem('memoria-storage-test');}catch{alert('O armazenamento está indisponível. Permita salvar dados do site antes de iniciar.');return;}const data=new FormData(e.target);session={id:crypto.randomUUID(),version:VERSION,date:new Date().toISOString(),list:nextList(records),digits:0,immediate:0,delayed:0,delaySeconds:300,answers:{immediate:'',delayed:''},math:{attempted:0,correct:0},context:{sleep:Number(data.get('sleep')),stress:data.get('stress'),notes:data.get('notes')}};digitTrial(0);};}
function screen(title,body){render(`<section class="card test"><span class="eyebrow">Sessão em andamento</span><h2>${title}</h2>${body}<p><button class="secondary" id="cancel">Cancelar sessão</button></p></section>`);document.querySelector('#cancel').onclick=()=>{if(confirm('Cancelar? Esta sessão não será registrada.'))abort();};}
function abort(){stop();session=null;render('<section class="card"><h2>Sessão interrompida</h2><p>Esta sessão não foi registrada. Mudanças de tela ou atrasos alteram os tempos do protocolo. Recomece em outro momento; a exposição às tarefas pode influenciar uma repetição.</p><button id="home">Voltar ao início</button></section>');document.querySelector('#home').onclick=home;}
function timer(ms,update){return new Promise(resolve=>{const start=performance.now();let previous=start;cancelTimer=()=>resolve(false);tick=setInterval(()=>{const now=performance.now();if(now-previous>2000){abort();return;}previous=now;const left=Math.max(0,ms-(now-start));update?.(left);if(!left){clearInterval(tick);tick=null;cancelTimer=null;resolve(true);}},50);});}
async function present(items,ms){for(const item of items){const el=document.querySelector('#stimulus');if(!session||!el)return false;el.textContent=item;if(!await timer(ms))return false;el.textContent='·';if(!await timer(250))return false;}return true;}
async function digitTrial(index){if(!session)return;if(index===6){encode();return;}screen(`Dígitos · ${index+1} de 6`,'<p>Memorize os dígitos na ordem apresentada.</p><div class="stimulus" id="stimulus">Prepare-se</div>');if(!await timer(1000))return;const sequence=digits(3+Math.floor(index/2));if(!await present([...sequence],1000))return;screen('Qual era a sequência?','<p>Digite na mesma ordem. Você tem 15 segundos.</p><form id="answer"><label>Sequência<input id="response" inputmode="numeric" pattern="[0-9]*" autocomplete="off" maxlength="5" autofocus></label><button>Confirmar</button></form><p class="timer" id="time"></p>');let answered=false;const submit=()=>{if(answered||!session)return;answered=true;const value=document.querySelector('#response').value;stop();if(value===sequence)session.digits++;digitTrial(index+1);};document.querySelector('#answer').onsubmit=e=>{e.preventDefault();submit();};if(await timer(15000,left=>document.querySelector('#time').textContent=`${Math.ceil(left/1000)} s`))submit();}
async function encode(){screen('Agora, oito palavras','<p>Memorize cada palavra. Depois, escreva as que lembrar, em qualquer ordem.</p><div class="stimulus" id="stimulus">Prepare-se</div>');if(!await timer(3000))return;if(!await present(WORDS[session.list],2000))return;recall(false);}
async function recall(delayed){screen(delayed?'Quais palavras você ainda lembra?':'Quais palavras você acabou de ver?',`<p>Escreva uma palavra por linha, em qualquer ordem. A etapa termina automaticamente em 60 segundos. Não consulte anotações.</p><label>Palavras lembradas<textarea id="recall" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="1000"></textarea></label><p class="timer" id="time" role="timer"></p>`);if(!await timer(60000,left=>document.querySelector('#time').textContent=`${Math.ceil(left/1000)} s restantes`))return;const stage=delayed?'delayed':'immediate';session.answers[stage]=document.querySelector('#recall').value;session[stage]=scoreRecall(session.answers[stage],WORDS[session.list]);if(delayed)finish();else distract();}
async function distract(){const start=performance.now();screen('Uma pausa com atenção','<p>Resolva as contas durante cinco minutos. Não repita mentalmente as palavras. O total de respostas e acertos aparecerá no resultado, separado da memória.</p><div class="stimulus" id="problem"></div><form id="math"><label>Resposta<input id="math-answer" inputmode="numeric" pattern="[0-9]+" required autocomplete="off"></label><button>Responder e continuar</button></form><p id="math-count" role="status">0 contas respondidas</p><p class="timer" id="time"></p>');let expected;function problem(){const a=Math.floor(Math.random()*30)+10,b=Math.floor(Math.random()*20)+1;expected=a+b;document.querySelector('#problem').textContent=`${a} + ${b}`;document.querySelector('#math-answer').value='';}problem();document.querySelector('#math').onsubmit=e=>{e.preventDefault();if(performance.now()-start>=300000)return;if(recordMathAnswer(session.math,document.querySelector('#math-answer').value,expected)){document.querySelector('#math-count').textContent=`${session.math.attempted} contas respondidas`;problem();document.querySelector('#math-answer').focus();}};if(!await timer(300000,left=>{const secs=Math.ceil(left/1000);document.querySelector('#time').textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')} restantes`;}))return;session.delaySeconds=Math.round((performance.now()-start)/1000);recall(true);}

function review(result){
 const words=WORDS[result.list];
 const stage=(key,title)=>{const detail=recallDetails(result.answers[key],words);return `<h3>${title}</h3><p><strong>Lembradas:</strong> ${detail.remembered.map(escape).join(', ')||'Nenhuma'}.</p><p class="note"><strong>Faltaram:</strong> ${detail.missing.map(escape).join(', ')||'Nenhuma — você lembrou todas'}.</p><details><summary>O que você escreveu</summary><p style="white-space:pre-wrap">${escape(result.answers[key])||'(Em branco)'}</p></details>`;};
 return `<section class="card"><h2>Contas nos cinco minutos</h2>${result.math?`<p><strong>${result.math.attempted}</strong> respondidas · <strong>${result.math.correct}</strong> certas · <strong>${result.math.attempted-result.math.correct}</strong> erradas.</p><small>Respostas enviadas durante o intervalo. Contas separadas da pontuação de memória.</small>`:'<p>A versão usada nesta sessão não registrava as contas.</p>'}</section><section class="card"><h2>As oito palavras</h2><div class="row">${words.map(word=>`<span class="pill">${escape(word)}</span>`).join('')}</div>${result.answers?stage('immediate','Lembrança imediata')+stage('delayed','Após cinco minutos'):'<p>Esta sessão antiga salvou a lista e as notas, mas não as respostas. Você pode conferir as oito palavras acima; não é possível identificar automaticamente qual faltou.</p>'}<p class="muted">O gabarito aparece somente depois da sessão completa. Acentos e letras maiúsculas não alteram a correção; erros de digitação podem contar como palavra ausente.</p></section>`;
}

function finish(){const result=session;session=null;const updated=[...records,result];let saved=false;try{validateRecords(updated);localStorage.setItem(KEY,JSON.stringify(updated));records=updated;saved=true;}catch{}render(`<section class="hero"><span class="eyebrow">Sessão concluída</span><h1>Mais um registro no tempo.</h1><p>${saved?'Seu resultado foi salvo neste aparelho.':'Não foi possível salvar. Exporte o resultado agora para não perdê-lo.'}</p></section><div class="grid"><div class="card"><h3>Sequências corretas</h3><span class="number">${result.digits}/6</span></div><div class="card"><h3>Lembrança imediata</h3><span class="number">${result.immediate}/8</span></div><div class="card tint"><h3>Após cinco minutos</h3><span class="number">${result.delayed}/8</span></div></div>${review(result)}<p>Variações isoladas não indicam melhora ou piora clínica. Compare sessões em condições semelhantes e leve suas preocupações a um profissional.</p><div class="row"><button id="home">Ver histórico</button><button class="secondary" id="backup">Exportar backup</button></div>`);document.querySelector('#home').onclick=home;document.querySelector('#backup').onclick=()=>download(JSON.stringify(updated,null,2),'memoria-backup.json');}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&session)abort();});
window.addEventListener('pagehide',()=>{if(session)abort();});
window.addEventListener('beforeunload',event=>{if(session){event.preventDefault();event.returnValue='';}});
home();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
