import {VERSION,WEEK_MS,wordsFor,isPending,canFollowup,canReveal,visualRound,scoreRecall,recallDetails,nextList,digits,validateRecords,mergeRecords} from './core.js';
const app=document.querySelector('#app'), KEY='memoria-em-dia-v1';
let records=[],storageError='',session=null,tick=null,cancelTimer=null,followupId=null;
try{records=validateRecords(JSON.parse(localStorage.getItem(KEY)||'[]'));}catch{storageError='Não foi possível ler o histórico. Exporte os dados originais antes de continuar; não sobrescreveremos seu histórico.';}
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>new Date(value).toLocaleDateString('pt-BR',{day:'2-digit',month:'short',year:'numeric'});
function stop(){clearInterval(tick);tick=null;if(cancelTimer){const cancel=cancelTimer;cancelTimer=null;cancel();}}
function render(html){app.innerHTML=html;window.scrollTo(0,0);}
function download(content,name){const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function home(){stop();session=null;followupId=null;const last=records.at(-1);render(`
 <section class="hero"><span class="eyebrow">Acompanhamento de memória</span><h1>Um momento de atenção.<br>Um registro no tempo.</h1><p>Observe seu desempenho em tarefas de memória imediata e após alguns minutos, sempre com a mesma sequência.</p><div class="row"><button id="start" ${storageError||records.some(isPending)?'disabled':''}>Começar sessão · protocolo 2 →</button><span class="muted">9–10 minutos hoje · 1 minuto após 7 dias</span></div></section>
 ${storageError?`<p class="error">${escape(storageError)}</p>`:''}
 ${pendingCards()}<div class="grid"><section class="card"><span class="eyebrow">Sessões registradas</span><p class="number">${records.length}</p><small>Histórico neste aparelho</small></section><section class="card"><span class="eyebrow">Última sessão</span><p class="number" style="font-size:26px">${last?date(last.date):'Ainda não há'}</p><small>${last?'Protocolo '+last.version:'Seu primeiro registro começa aqui'}</small></section><section class="card tint"><span class="eyebrow">Ritmo sugerido</span><p class="number">Semanal</p><small>Uma convenção do app, sem validação clínica</small></section></div>
 <section class="card"><h2>O que você vai fazer</h2><p>1. Repetir seis sequências de dígitos.<br>2. Ver 12 palavras e escrever as que lembrar.<br>3. Encontrar diferenças entre quadros de símbolos por cinco minutos.<br>4. Escrever novamente as palavras que lembrar.<br>5. Voltar após sete dias para uma última lembrança, antes de ver o gabarito.</p><p class="note">Protocolo experimental com execução fixa, sem normas clínicas. Repetição, dificuldade das listas, sono e atenção afetam o resultado. O app não determina se sua memória está piorando. O protocolo 2 acrescenta uma revisão após sete dias. Os resultados de 8 e 12 palavras ficam separados.</p><details><summary>Como manter sessões comparáveis</summary><p>Use o mesmo aparelho, em horário e ambiente semelhantes. Reserve nove minutos, ative Não Perturbe e evite ajuda, anotações, capturas de tela ou ensaio das palavras. Sair do app interrompe a sessão. As listas se alternam, mas não têm dificuldade equivalente comprovada; a primeira sessão também envolve familiarização.</p><p>Se perceber piora persistente ou dificuldades nas atividades do dia a dia, procure avaliação profissional, mesmo com bons resultados aqui.</p><p>Referências: <a href="https://www.nia.nih.gov/health/health-care-professionals-information/assessing-cognitive-impairment-older-patients" target="_blank" rel="noopener">National Institute on Aging</a> e <a href="https://www.nice.org.uk/guidance/ng97/chapter/Recommendations" target="_blank" rel="noopener">NICE</a>. Elas orientam a interpretação e a busca de avaliação; não validam este protocolo.</p></details></section>
 <section class="card"><h2>Seu histórico</h2><p>Resultados por tarefa, sem nota global ou classificação de saúde.</p>${historyTables()}<div class="row" style="margin-top:24px"><button class="secondary" id="export">Exportar backup</button><label class="button secondary" for="import">Restaurar backup</label><input type="file" id="import" accept="application/json,.json" hidden style="display:none"></div><p id="import-status" role="status"></p><small>Dados apenas neste navegador, sem envio ao servidor. Limpar os dados do site ou trocar de aparelho pode apagar o histórico. Exporte backups para o app Arquivos. O Safari e o app da Tela de Início podem ter históricos separados.</small></section>
 <details><summary>Adicionar ao iPhone</summary><p>Com o site publicado em HTTPS, abra no Safari → Compartilhar → Adicionar à Tela de Início → Adicionar. Abra uma vez com internet para preparar o uso offline. Faça as sessões sempre pelo mesmo atalho.</p></details>`);
 document.querySelector('#start').onclick=setup;
 document.querySelectorAll('[data-followup]').forEach(button=>button.onclick=()=>prepareFollowup(button.dataset.followup));
 document.querySelectorAll('[data-review]').forEach(button=>button.onclick=()=>{const result=records.find(r=>r.id===button.dataset.review);render(`<section class="hero"><span class="eyebrow">Sessão de ${date(result.date)}</span><h1>As palavras da sua sessão.</h1></section>${review(result)}<button id="home">Voltar ao histórico</button>`);document.querySelector('#home').onclick=home;});
 document.querySelector('#export').onclick=()=>download(storageError?(localStorage.getItem(KEY)||'[]'):JSON.stringify(records,null,2),'memoria-backup.json');
 document.querySelector('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('Arquivo muito grande.');if(storageError)throw Error('Exporte o histórico original antes de reparar o armazenamento.');const incoming=validateRecords(JSON.parse(await file.text()));const merged=mergeRecords(records,incoming);localStorage.setItem(KEY,JSON.stringify(merged));records=merged;home();document.querySelector('#import-status').textContent='Backup restaurado; sessões existentes preservadas.';}catch(error){document.querySelector('#import-status').textContent=error.message;}};
}
function setup(){if(records.some(isPending)){home();return;}render(`<section class="card"><span class="eyebrow">Antes de começar</span><h1>Como você está hoje?</h1><p>Reserve de nove a dez minutos agora e volte após sete dias. O gabarito e suas respostas ficarão ocultos até a revisão. Os tempos são fixos. Mantenha o app aberto e não consulte anotações.</p>${records.length&&Date.now()-Date.parse(records.at(-1).date)<6*86400000?'<p class="note">Você fez uma sessão recentemente. A prática pode melhorar os resultados; considere manter o intervalo semanal.</p>':''}<form id="setup"><label>Horas de sono na última noite<input name="sleep" type="number" min="0" max="24" step="0.5" required placeholder="Ex.: 7.5"></label><label>Estresse agora<select name="stress"><option>Baixo</option><option>Médio</option><option>Alto</option></select></label><label>Observações (opcional)<input name="notes" maxlength="500" placeholder="Ex.: cansaço, mudança de rotina"></label><p>Você verá um dígito por vez. Depois, digite a sequência na mesma ordem. Serão duas sequências de cada tamanho: 3, 4 e 5 dígitos.</p><div class="row"><button>Iniciar teste</button><button type="button" class="secondary" id="back">Voltar</button></div></form></section>`);document.querySelector('#back').onclick=home;document.querySelector('#setup').onsubmit=e=>{e.preventDefault();try{localStorage.setItem('memoria-storage-test','1');localStorage.removeItem('memoria-storage-test');}catch{alert('O armazenamento está indisponível. Permita salvar dados do site antes de iniciar.');return;}const data=new FormData(e.target);session={id:crypto.randomUUID(),version:VERSION,date:new Date().toISOString(),list:nextList(records),digits:0,immediate:0,delayed:0,delaySeconds:300,answers:{immediate:'',delayed:''},visual:{attempted:0,correct:0},followup:{status:'pending'},context:{sleep:Number(data.get('sleep')),stress:data.get('stress'),notes:data.get('notes')}};digitTrial(0);};}
function screen(title,body){render(`<section class="card test"><span class="eyebrow">Sessão em andamento</span><h2>${title}</h2>${body}<p><button class="secondary" id="cancel">Cancelar sessão</button></p></section>`);document.querySelector('#cancel').onclick=()=>{if(confirm(followupId?'Encerrar a revisão sem nota? Não será possível repetir esta tentativa.':'Cancelar? Esta sessão não será registrada.'))abort();};}
function abort(){stop();if(followupId){interruptFollowup();return;}session=null;render('<section class="card"><h2>Sessão interrompida</h2><p>Esta sessão não foi registrada. Mudanças de tela ou atrasos alteram os tempos do protocolo. Recomece em outro momento; a exposição às tarefas pode influenciar uma repetição.</p><button id="home">Voltar ao início</button></section>');document.querySelector('#home').onclick=home;}
function timer(ms,update){return new Promise(resolve=>{const start=performance.now();let previous=start;cancelTimer=()=>resolve(false);tick=setInterval(()=>{const now=performance.now();if(now-previous>2000){abort();return;}previous=now;const left=Math.max(0,ms-(now-start));update?.(left);if(!left){clearInterval(tick);tick=null;cancelTimer=null;resolve(true);}},50);});}
async function present(items,ms){for(const item of items){const el=document.querySelector('#stimulus');if(!session||!el)return false;el.textContent=item;if(!await timer(ms))return false;el.textContent='·';if(!await timer(250))return false;}return true;}
async function digitTrial(index){if(!session)return;if(index===6){encode();return;}screen(`Dígitos · ${index+1} de 6`,'<p>Memorize os dígitos na ordem apresentada.</p><div class="stimulus" id="stimulus">Prepare-se</div>');if(!await timer(1000))return;const sequence=digits(3+Math.floor(index/2));if(!await present([...sequence],1000))return;screen('Qual era a sequência?','<p>Digite na mesma ordem. Você tem 15 segundos.</p><form id="answer"><label>Sequência<input id="response" inputmode="numeric" pattern="[0-9]*" autocomplete="off" maxlength="5" autofocus></label><button>Confirmar</button></form><p class="timer" id="time"></p>');let answered=false;const submit=()=>{if(answered||!session)return;answered=true;const value=document.querySelector('#response').value;stop();if(value===sequence)session.digits++;digitTrial(index+1);};document.querySelector('#answer').onsubmit=e=>{e.preventDefault();submit();};if(await timer(15000,left=>document.querySelector('#time').textContent=`${Math.ceil(left/1000)} s`))submit();}
async function encode(){screen('Agora, 12 palavras','<p>Memorize cada palavra. Depois, escreva as que lembrar, em qualquer ordem.</p><div class="stimulus" id="stimulus">Prepare-se</div>');if(!await timer(3000))return;if(!await present(wordsFor(session),2000))return;session.encodedAt=new Date().toISOString();recall(false);}
async function recall(delayed){screen(delayed?'Quais palavras você ainda lembra?':'Quais palavras você acabou de ver?',`<p>Escreva uma palavra por linha, em qualquer ordem. A etapa termina automaticamente em 60 segundos. Não consulte anotações.</p><label>Palavras lembradas<textarea id="recall" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="1000"></textarea></label><p class="timer" id="time" role="timer"></p>`);if(!await timer(60000,left=>document.querySelector('#time').textContent=`${Math.ceil(left/1000)} s restantes`))return;const stage=delayed?'delayed':'immediate';session.answers[stage]=document.querySelector('#recall').value;session[stage]=scoreRecall(session.answers[stage],wordsFor(session));if(delayed)finish();else distract();}
async function distract(){
 screen('Encontre a diferença','<p>Compare os dois quadros e toque, no quadro da direita, no símbolo diferente. Continue por cinco minutos, sem ensaiar as palavras.</p><div id="visual"></div><p id="visual-count" role="status">0 quadros respondidos</p><p class="timer" id="time"></p>');
 const start=performance.now();const symbols=['●','▲','■','✚'];
 function round(){const puzzle=visualRound();document.querySelector('#visual').innerHTML=`<div class="visual-pair"><div><h3>Modelo</h3><div class="symbol-grid">${puzzle.left.map(s=>`<span class="symbol-cell" aria-hidden="true">${symbols[s]}</span>`).join('')}</div></div><div><h3>Toque na diferença</h3><div class="symbol-grid">${puzzle.right.map((s,i)=>`<button class="symbol-cell" data-cell="${i}" aria-label="Posição ${i+1}: ${['círculo','triângulo','quadrado','cruz'][s]}">${symbols[s]}</button>`).join('')}</div></div></div>`;
 document.querySelectorAll('[data-cell]').forEach(button=>button.onclick=()=>{if(!session||performance.now()-start>=300000)return;session.visual.attempted++;if(Number(button.dataset.cell)===puzzle.changed)session.visual.correct++;document.querySelector('#visual-count').textContent=`${session.visual.attempted} quadros respondidos`;round();});}
 round();if(!await timer(300000,left=>{const secs=Math.ceil(left/1000);document.querySelector('#time').textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')} restantes`;}))return;
 session.delaySeconds=Math.round((performance.now()-start)/1000);recall(true);
}

function review(result){
 if(!canReveal(result,records))return `<section class="card tint"><h2>Gabarito reservado para depois da revisão</h2><p>As palavras e suas respostas ficam ocultas enquanto esta lista tem uma revisão pendente. Volte ao início para consultar a data.</p>${distractionResult(result)}</section>`;
 const words=wordsFor(result);
 const stage=(key,title)=>{const detail=recallDetails((key==='followup'?result.followup.answer:result.answers[key]),words);return `<h3>${title}</h3><p><strong>Lembradas:</strong> ${detail.remembered.map(escape).join(', ')||'Nenhuma'}.</p><p class="note"><strong>Faltaram:</strong> ${detail.missing.map(escape).join(', ')||'Nenhuma — você lembrou todas'}.</p><details><summary>O que você escreveu</summary><p style="white-space:pre-wrap">${escape(key==='followup'?result.followup.answer:result.answers[key])||'(Em branco)'}</p></details>`;};
 return `<section class="card">${distractionResult(result)}</section><section class="card"><h2>As ${words.length} palavras</h2><div class="row">${words.map(word=>`<span class="pill">${escape(word)}</span>`).join('')}</div>${result.answers?stage('immediate','Lembrança imediata')+stage('delayed','Após cinco minutos')+(result.followup?.status==='completed'?stage('followup','Revisão após dias'):''):'<p>Esta sessão antiga salvou a lista e as notas, mas não as respostas. Você pode conferir as oito palavras acima; não é possível identificar automaticamente qual faltou.</p>'}<p class="muted">No protocolo 2, o gabarito é liberado após a revisão tardia (ou sua interrupção definitiva). Acentos e letras maiúsculas não alteram a correção; erros de digitação podem contar como palavra ausente.</p></section>`;
}

function finish(){const result=session;session=null;const updated=[...records,result];let saved=false;try{validateRecords(updated);localStorage.setItem(KEY,JSON.stringify(updated));records=updated;saved=true;}catch{}render(`<section class="hero"><span class="eyebrow">Sessão concluída</span><h1>Mais um registro no tempo.</h1><p>${saved?'Seu resultado foi salvo neste aparelho.':'Não foi possível salvar. Exporte o resultado agora para não perdê-lo.'}</p></section><div class="grid"><div class="card"><h3>Sequências corretas</h3><span class="number">${result.digits}/6</span></div><div class="card"><h3>Lembrança imediata</h3><span class="number">${result.immediate}/${wordsFor(result).length}</span></div><div class="card tint"><h3>Após cinco minutos</h3><span class="number">${result.delayed}/${wordsFor(result).length}</span></div></div>${result.version===VERSION?`<section class="card tint"><h2>Seu próximo passo: voltar após sete dias</h2><p>A partir de ${dateTime(Date.parse(result.encodedAt)+WEEK_MS)}. O app não envia notificações; anote apenas essa data no calendário.</p></section>`:""}${review(result)}<p>Variações isoladas não indicam melhora ou piora clínica. Compare sessões em condições semelhantes e leve suas preocupações a um profissional.</p><div class="row"><button id="home">Ver histórico</button><button class="secondary" id="backup">Exportar backup</button></div>`);document.querySelector('#home').onclick=home;document.querySelector('#backup').onclick=()=>download(JSON.stringify(updated,null,2),'memoria-backup.json');}
const dateTime=value=>new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
function distractionResult(r){const v=r.version===VERSION?r.visual:r.math;return `<h2>${r.version===VERSION?'Distração visual':'Contas'} nos cinco minutos</h2>${v?`<p>${v.attempted} respostas · ${v.correct} acertos · ${v.attempted-v.correct} erros.</p><small>Resultado separado da memória.</small>`:'<p>Não registrado nesta sessão.</p>'}`;}
function pendingCards(){return records.filter(isPending).map(r=>`<section class="card tint"><span class="eyebrow">Ciclo de sete dias em andamento</span><h2>${canFollowup(r)?'Sua revisão está disponível':'Sua revisão tem data marcada'}</h2><p>Sessão de ${date(r.date)}. Retorne a partir de <strong>${dateTime(Date.parse(r.encodedAt)+WEEK_MS)}</strong>, por um minuto. Atrasos serão registrados.</p><p>Conclua esta revisão antes de iniciar outra lista. Não consulte nem ensaie as palavras. Não há notificação automática: anote somente a data no seu calendário.</p><button data-followup="${escape(r.id)}">${canFollowup(r)?'Fazer revisão':'Conferir disponibilidade'}</button></section>`).join('');}
function historyTables(){if(!records.length)return '<p>Nenhuma sessão ainda.</p>';return ['2.0','1.0'].map(version=>{const group=records.filter(r=>r.version===version);if(!group.length)return '';return `<h3>Protocolo ${version} · ${version==='2.0'?'12 palavras e distração visual':'8 palavras e contas'}</h3><p>Compare resultados apenas dentro deste protocolo.</p><div class="table-wrap"><table><thead><tr><th>Data</th><th>Dígitos</th><th>Imediata</th><th>Após 5 min</th><th>Após dias</th><th>Sono / estresse</th><th>Observações</th><th>Detalhes</th></tr></thead><tbody>${[...group].reverse().map(r=>`<tr><td>${date(r.date)}</td><td>${r.digits}/6</td><td>${r.immediate}/${wordsFor(r).length}</td><td>${r.delayed}/${wordsFor(r).length}</td><td>${r.followup?.status==='completed'?`${r.followup.score}/12 · ${(r.followup.elapsedSeconds/86400).toFixed(2)} dias${Object.values(r.followup.context).some(v=>v===true)?' · houve consulta/anotação/ensaio':''}`:r.followup?.status==='interrupted'?'Interrompida · sem nota':r.followup?'Pendente':'Não se aplica'}</td><td>${r.context.sleep} h / ${escape(r.context.stress)}</td><td>${escape(r.context.notes)}</td><td><button class="secondary" data-review="${escape(r.id)}">${canReveal(r,records)?'Ver palavras':'Gabarito bloqueado'}</button></td></tr>`).join('')}</tbody></table></div>`;}).join('');}
function saveRecords(updated){validateRecords(updated);localStorage.setItem(KEY,JSON.stringify(updated));records=updated;}
function prepareFollowup(id){const r=records.find(r=>r.id===id);if(!r||!canFollowup(r)){home();return;}
 render(`<section class="card"><span class="eyebrow">Revisão da sessão de ${date(r.date)}</span><h1>O que ficou na memória?</h1><p>Você terá 60 segundos para escrever as palavras da sessão, sem consultar nenhuma lista. O intervalo real será registrado. Esta tentativa é única: se sair ou cancelar depois de iniciar, ficará como interrompida, sem nota.</p><form id="followup-setup"><label class="check"><input name="consulted" type="checkbox">Consultei as palavras ou minhas respostas desde a sessão</label><label class="check"><input name="noted" type="checkbox">Anotei ou fotografei as palavras</label><label class="check"><input name="rehearsed" type="checkbox">Repeti ou ensaiei as palavras desde a sessão</label><label>Observações sobre o intervalo<input name="notes" maxlength="500" placeholder="Ex.: sono, distrações, mudanças na rotina"></label><div class="row"><button>Iniciar revisão de 60 segundos</button><button type="button" class="secondary" id="home">Voltar</button></div><p id="followup-error" role="status"></p></form></section>`);
 document.querySelector('#home').onclick=home;
 document.querySelector('#followup-setup').onsubmit=e=>{e.preventDefault();if(!canFollowup(r)){home();return;}const form=new FormData(e.target);const startedAt=new Date().toISOString();const updated={...r,followup:{status:'started',startedAt,elapsedSeconds:Math.round((Date.parse(startedAt)-Date.parse(r.encodedAt))/1000),context:{consulted:form.has('consulted'),noted:form.has('noted'),rehearsed:form.has('rehearsed'),notes:form.get('notes')}}};try{saveRecords(records.map(item=>item.id===id?updated:item));}catch{document.querySelector('#followup-error').textContent='Não foi possível salvar o início da revisão. Libere o armazenamento antes de tentar.';return;}followupId=id;runFollowup(updated);};
}
async function runFollowup(r){screen('Quais palavras você lembra daquela sessão?','<p>Escreva uma palavra por linha. Você tem 60 segundos, sem consultas.</p><label>Palavras lembradas<textarea id="followup-answer" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="1000"></textarea></label><p class="timer" id="time" role="timer"></p>');
 if(!await timer(60000,left=>document.querySelector('#time').textContent=`${Math.ceil(left/1000)} s restantes`))return;
 const answer=document.querySelector('#followup-answer').value;const completed={...r,followup:{...r.followup,status:'completed',answer,score:scoreRecall(answer,wordsFor(r)),completedAt:new Date().toISOString()}};
 followupId=null;finalizeFollowup(completed);
}
function finalizeFollowup(r){const updated=records.map(item=>item.id===r.id?r:item);let saved=true;try{saveRecords(updated);}catch{records=updated;saved=false;}
 render(`<section class="hero"><span class="eyebrow">Revisão ${r.followup.status==='completed'?'concluída':'interrompida'}</span><h1>${r.followup.status==='completed'?`${r.followup.score} de 12 palavras`:'Revisão sem pontuação'}</h1><p>${saved?'Registro salvo neste aparelho.':'Não foi possível salvar. Exporte o backup agora para preservar este resultado.'} Intervalo real: ${(r.followup.elapsedSeconds/86400).toFixed(2)} dias (${dateTime(r.followup.startedAt)}).</p>${r.followup.status==='interrupted'?'<p>A tentativa foi encerrada definitivamente, pois repetir a recuperação pode influenciar o resultado. O gabarito está liberado.</p>':''}<p>Durante o intervalo: consulta ${r.followup.context.consulted?'sim':'não'} · anotações ${r.followup.context.noted?'sim':'não'} · ensaio ${r.followup.context.rehearsed?'sim':'não'}. ${escape(r.followup.context.notes)}</p></section>${review(r)}<div class="row"><button id="home">Ver histórico</button><button class="secondary" id="backup">Exportar backup</button></div>`);
 document.querySelector('#home').onclick=home;document.querySelector('#backup').onclick=()=>download(JSON.stringify(updated,null,2),'memoria-backup.json');
}
function interruptFollowup(){const r=records.find(r=>r.id===followupId);followupId=null;if(r)finalizeFollowup({...r,followup:{...r.followup,status:'interrupted'}});}
// A persisted start is a consumed attempt even if the browser closed abruptly.
if(records.some(r=>r.followup?.status==='started')){try{saveRecords(records.map(r=>r.followup?.status==='started'?{...r,followup:{...r.followup,status:'interrupted'}}:r));}catch{storageError='Não foi possível recuperar a revisão interrompida. Exporte o backup antes de continuar.';}}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(session||followupId))abort();});
window.addEventListener('pagehide',()=>{if(session||followupId)abort();});
window.addEventListener('beforeunload',event=>{if(session||followupId){event.preventDefault();event.returnValue='';}});
home();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
